cleanarchitecture:
  applicationName: Sanbox-spring-boot

server:
  port: 8088

app:
  gateway:
    req-res:
      baseUrl: "https://reqres.in/api"
    welcome:
      baseUrl: "app"
      path: "general path"